---
title: "Portfolio 5"
author: "Line and Solvej"
date: "23 maj 2018"
---

# data clean
```{r}
setwd("C:/Users/Bruger/Google Drev/Cognitive Science/Social and cultural cognition/Exam")
library(pacman)
p_load(ggplot2,rethinking,brms,readxl,rstan,tidyverse,dplyr,pastecs,readr)

data <- read.table("data_max.txt", comment.char = "#", sep=",", header = T)
data <- select(data,-X)

data <- subset(data, data$task=='complex')
data$proportion <- as.numeric(data$proportion) 
data$proportion <- scale(data$proportion)
data$network <- as.numeric(data$network)

```

# models
```{r}

#baseline model uninformative
M0u <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a,
    a ~ dnorm(0.5,0.2),
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M0u)
plot(precis(M0u))

#proportion model uninformative
M1u <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bP*proportion,
    a ~ dnorm(0.5,0.2),
    bP ~ dnorm(0,0.4), 
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M1u)
plot(precis(M1u))

#proportion model concervative
M1c <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bP*proportion,
    a ~ dnorm(0.5,0.2),
    bP ~ dnorm(0,0.1), 
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M1c)
plot(precis(M1c))

#network model uninformative
M2u <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bN*network,
    a ~ dnorm(0.5,0.2),
    bN ~ dnorm(0,0.3), 
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M2u)
plot(precis(M2u))

#network model concervative
M2c <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bN*network,
    a ~ dnorm(0.5,0.2),
    bN ~ dnorm(0,0.1), 
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M2c)
plot(precis(M2c))

#network+proportion model conservative
M3 <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bN*network + bP*proportion,
    a ~ dnorm(0.5,0.2),
    bN ~ dnorm(0,0.1), 
    bP ~ dnorm(0,0.1),
    sigma ~ dcauchy(0,1)
  ),
data = data)

# print results
precis(M3)
plot(precis(M3))

#network*proportion model conservative
M4 <- rethinking::map(
  alist(
    mean_payoff_all ~ dnorm(mu,sigma),
    mu <- a + bN*network + bP*proportion + bNP*network*proportion,
    a ~ dnorm(0.5,0.2),
    bN ~ dnorm(0,0.1), 
    bP ~ dnorm(0,0.1),
    bNP ~ dnorm(0,0.1), 
    sigma ~ dcauchy(0,1)
  ), 
data = data)

# print results
precis(M4)
plot(precis(M4))

```

# model comparison
```{r}

#model comparison 
(models <- compare(M0u,M1c,M2c,M3,M4))
# M4 WIN BIG TIME!!

plot(models,SE=TRUE,dSE=T)

plot(coeftab(M3,M4))


```

# model quality
```{r}

pp_check(M4)

plot(postcheck(M4))

# plot map posterior / model line 
post <- extract.samples(M4, n=100)

plot(mean_payoff_all ~ network*proportion, data = data)+
  abline(a=coef(M4)["a"],b=coef(M4)["bNP"])

for (i in 1:20) 
  abline(a=post$a[i],b=post$bNP[i],col=col.alpha("black",0.3))

# posterior predictive plot
mu <- link(M4)
mu.mean <- apply(mu,2,mean)
mu.PI <- apply(mu,2,PI)

plot(mu.mean ~ data$mean_payoff_all, col=rangi2,ylim=range(mu.PI),
     xlab="observed payoff", ylab="predicted payoff")
abline(a=0,b=1,lty=2)
for (i in 1:nrow(data))
  lines(rep(data$mean_payoff_all[i],2),c(mu.PI[1,i],mu.PI[2,i]),
        col=rangi2)

# sim networks
sim_nn = sim(M4, data = data[data$network == '2',])
sim_fu = sim(M4, data = data[data$network == '1',])

dens(data$mean_payoff_all[data$network == "2"], add = F, col = 'deepskyblue')
dens(data$mean_payoff_all[data$network == '1'], add = T, col = 'deeppink')
dens(sim_nn, add = T,col = 'dodgerblue4')
dens(sim_fu, add= T, col = 'darkred')

data$network <- as.factor(data$network)

ggplot(data,aes(x=proportion,y=mean_payoff_all,colour=network))+
  geom_smooth()

```
 
# data visualisation (payoff as function of proportion pr network)
```{r}

# posterior map regression line and 89 PI, in two networks
seq_proportion <- seq(from=-1.5802402, to=-1.5802402, by=0.2)
mu.nn <- link(M4,data=data.frame(network=2,proportion=seq_proportion))
mu.nn.mean <- apply(mu.nn,2,mean)
mu.nn.PI <- apply(mu.nn,2,PI,prob=0.89)

mu.fu <- link(M4,data=data.frame(network=1,proportion=seq_proportion))
mu.fu.mean <- apply(mu.fu,2,mean)
mu.fu.PI <- apply(mu.fu,2,PI,prob=0.89)

nn <- data[data$network==2,]
plot(mean_payoff_all ~ proportion, data=nn,
     col=rangi2,ylab="mean payoff",xlab="proportion index")+
  mtext("nearest neighbour",3)+
  lines(seq_proportion,mu.nn.mean,col=rangi2)+
  shade(mu.nn.PI,seq_proportion,col=col.alpha(rangi2,0.3))

fully <- data[data$network==1,]
plot(mean_payoff_all ~ proportion, data=fully,
     col=rangi2,ylab="mean payoff",xlab="proportion index")+
  mtext("fully connected",3)+
  lines(seq_proportion,mu.fu.mean,col=rangi2)+
  shade(mu.fu.PI,seq_proportion,col=col.alpha(rangi2,0.3))


# simulations for plot 
sim.nn.2 <- sim(M4,data=data.frame(network=2,proportion=seq_proportion))
str(sim.nn.2)
nn.PI <- apply(sim.nn.2,2,PI,prob=0.89)
mu.nn.mean <- apply(mu.nn,2,mean)
mu.nn.HPDI <- apply(mu.nn,2,HPDI,prob=0.89)

# plot nearest neighbour
nn <- data[data$network==2,]
plot(mean_payoff_all ~ proportion, data=nn, col=col.alpha(rangi2,0.5))+
  lines(seq_proportion,mu.nn.mean)+
  shade(mu.nn.HPDI,seq_proportion)+
  shade(nn.PI,seq_proportion)


#plot data 
ggplot(data = nn, aes(x=proportion, y=mean_payoff_all))+
  geom_point()+
  geom_smooth()


```

# Uncertainty
```{r}
post <- extract.samples(M4)
interaction_nn <- post$bN + post$bNP*1
interaction_full <- post$bN + post$bNP*0

mean(interaction_nn)
mean(interaction_full)

dens(interaction_nn,xlim=c(-0.4,0.0),ylim=c(0,50),
     xlab="interaction effect",col=rangi2)
dens(interaction_full,add = T)

# no overlap -> very certain 

```


# trypych
```{r}
par(mfrow=c(1,3))
net_seq <- 1:2
for (i in -1:1){
  dt <- data[data$proportion==i,]
  plot(mean_payoff_all~network,data=dt,col=rangi2,
       main=paste("proportion",i),xlim=c(1,2),ylim=c(0,1),
       xlab="proportion index")
  mu <- link(M4,data=data.frame(proportion=i,network=net_seq))
  mu.mean <- apply(mu,2,mean)
  mu.PI <- apply(mu,2,PI,prob=0.89)
  lines(net_seq,mu.mean)
  lines(net_seq,mu.PI[1,],lty=2)
  lines(net_seq,mu.PI[2,],lty=2)
}


par(mfrow=c(1,3))
prop_seq <- -2:2
for (i in 1:2){
  dt <- data[data$network==i,]
  plot(mean_payoff_all~proportion,data=dt,col=rangi2,
       main=paste("network",i),xlim=c(-2,2),ylim=c(0,1),
       xlab="proportion index")
  mu <- link(M4,data=data.frame(network=i,proportion=prop_seq))
  mu.mean <- apply(mu,2,mean)
  mu.PI <- apply(mu,2,PI,prob=0.89)
  lines(prop_seq,mu.mean)
  lines(prop_seq,mu.PI[1,],lty=2)
  lines(prop_seq,mu.PI[2,],lty=2)
}



```


